<!DOCTYPE html>
<html>
<head>
    <title>Регистрация</title>
    <link rel="stylesheet" type="text/css" href="/styles.css">
</head>
<body>
<h1>Регистрация</h1>
<form action="/register" method="post">
    Логин: <input type="text" name="username"/><br><br>
    Пароль: <input type="password" name="password"/><br><br>
    Подтвердите пароль: <input type="password" name="confirmPassword"/><br><br>
    <input type="submit" value="Зарегистрироваться"/>
</form>
</body>
</html>
